### ISSUE TITLE
ClusteringManager crashing

### ISSUE THREAD

**Issue by VSmallbon** [efremidze/Cluster#28]
I'm having a problem with my program crashing while using clustering manager. I'm trying to build an app that will display the status of houses using coloured icons. 
![screen shot 2017-06-29 at 3 39 38 pm](https://user-images.githubusercontent.com/2358842/27672944-65f35fe8-5ce1-11e7-9424-d3f37a3ec893.png)

It gives me an index out of range error when the map reloads, however the error only occurs occasionally. I can't tell from the stack trace where the error is occuring, since it takes me to a line Cluster.swift. Does anyone have any idea on what sort of thing could be causing the error? I have no idea what array could be out of range to cause this error. 

![screen shot 2017-06-29 at 3 55 35 pm](https://user-images.githubusercontent.com/2358842/27673339-7117563e-5ce3-11e7-8ec6-719d16a39b55.png)

I'm thought the error is coming from the function below (as it sets the MKAnnotationView) but I swapped it for the function in the example project and it still crashes. 

    //Display annotations and pins for the map
    func mapView(_ mapView: MKMapView, viewFor annotation: MKAnnotation) -> MKAnnotationView? {

        var reuseId = ""
        let orangeColor = UIColor(red: 255/255, green: 149/255, blue: 0/255, alpha: 1)
        let redColor = UIColor(red: 255/255, green: 0/255, blue: 0/255, alpha: 1)
        let greenColor = UIColor(red: 6/255, green: 152/255, blue: 6/255, alpha: 1)
        
        if let annotation = annotation as? ClusterAnnotation {
            let identifier = "Cluster"
            var view = mapView.dequeueReusableAnnotationView(withIdentifier: identifier)
            if view == nil {
                if let annotation = annotation.annotations.first as? Annotation, let type = annotation.type {
                    view = BorderedClusterAnnotationView(annotation: annotation, reuseIdentifier: identifier, type: type, borderColor: .white)
                } else {
                    let allAnnos = annotation.annotations
                    if (!allAnnos.isEmpty && !addressStatus.isEmpty){
                        for anno in allAnnos {
                        if (addressStatus[anno.title!!] == "Offline") {
                            view = ClusterAnnotationView(annotation: annotation, reuseIdentifier: identifier, type: .color(redColor, radius: 25))

                            return view
                            
                        } else if (addressStatus[anno.title!!] == "Error"){
                            view = ClusterAnnotationView(annotation: annotation, reuseIdentifier: identifier, type: .color(orangeColor, radius: 25))

                            return view
                            
                        }
                        }
                    }
                    view = ClusterAnnotationView(annotation: annotation, reuseIdentifier: identifier, type: .color(greenColor, radius: 25))
                }
            } else {
                let allAnnos = annotation.annotations
                if (!allAnnos.isEmpty && !addressStatus.isEmpty) {
                    for anno in allAnnos {
                        if (addressStatus[anno.title!!] == "Offline") {

                            view = ClusterAnnotationView(annotation: annotation, reuseIdentifier: identifier, type: .color(redColor, radius: 25))

                            return view
                        
                        } else if (addressStatus[anno.title!!] == "Error"){

                            view = ClusterAnnotationView(annotation: annotation, reuseIdentifier: identifier, type: .color(orangeColor, radius: 25))

                            return view
                        
                        }
                    }
                    view = ClusterAnnotationView(annotation: annotation, reuseIdentifier: identifier, type: .color(greenColor, radius: 25))
                }
            }

            return view
            
        } else {
            reuseId = "Pin"
            var pinView = mapView.dequeueReusableAnnotationView(withIdentifier: reuseId)
                pinView = MKAnnotationView(annotation: annotation, reuseIdentifier: reuseId)
                pinView?.canShowCallout = true
                let address = annotation.title
            
                if (addressStatus[address!!] == "OK") {
                    pinView?.image = UIImage(named:"House Icon Green.png")!
                } else if (addressStatus[address!!] == nil) {
                    pinView?.image = UIImage(named:"House Icon Black.png")!
                } else if (addressStatus[address!!] == "Error") {
                    pinView?.image = UIImage(named:"House Icon Orange.png")!
                } else if (addressStatus[address!!] == "Offline") {
                    pinView?.image = UIImage(named:"House Icon Red.png")!
                }
    
            
                pinView?.frame = CGRect(x: 0, y: 0, width: 30, height: 30)
            
            return pinView
        }
    }

Any help would be greatly appreciated thank you!

**Comment by efremidze** [comment]
Ill take a look asap

**Comment by efremidze** [comment]
Try the latest commit from the master branch. I fixed a threading bug.

**Comment by VSmallbon** [comment]
I did a pod update but my project is still using Cluster 1.0.7? Is this the right version? I also can't see any recent commit messages on the master branch in git. The crash still occurs, so maybe I can't see the latest version?

**Comment by efremidze** [comment]
`pod 'Cluster', :git => 'https://github.com/efremidze/Cluster.git'`

**Comment by VSmallbon** [comment]
I'm still getting the crash even though I updated to the latest version. I'm retrieving lat long values in a url task, would that possibly be causing the crash?

    func getHomeStatus() -> Void {
        let todoEndpoint = "https://lxxxxx/status.php"
        guard let url = URL(string: todoEndpoint) else {
            print("Error: cannot create URL")
            return
        }
        let urlRequest = URLRequest(url: url)
        
        // set up the session
        let config = URLSessionConfiguration.default
        let session = URLSession(configuration: config)
        
        // make the request
        let task = session.dataTask(with: urlRequest) {
            (data, response, error) in
            // check for any errors
            guard error == nil else {
                print("error calling GET on /todos/1")
                return
            }
            // make sure we got data
            guard let responseData = data else {
                print("Error: did not receive data")
                return
            }
            
            // parse the result as JSON, since that's what the API provides
            
            let string1 = String(data: responseData, encoding: String.Encoding.utf8) ?? "Data could not be printed"
            
            let temp = self.convertToDictionary(text: string1) as! [String : String]
            if (temp != self.addressStatus){
                self.addressStatus = temp
                let annotations = self.mapView.annotations
                
                DispatchQueue.main.async {
                    
                    self.mapView.removeAnnotations(annotations)
                    self.mapView.addAnnotations(annotations)
                    self.mapView.reloadInputViews()
                }
                
            }
            
        }
        task.resume()
        
        
    }

**Comment by efremidze** [comment]
what is `mapView.reloadInputViews()`?

**Comment by VSmallbon** [comment]
It reloads the Map Kit View, however I think I found the problem. I have this function:

    override func viewWillAppear(_ animated: Bool) {
        self.mapView.showAnnotations(self.clusterManager.annotations, animated: true)
    }

Which I'm using to rezoom the map every time the user navigates back to the view. I've removed the need of this function from the code and I no longer get the index out of bounds error.

**Comment by efremidze** [comment]
So the problem is solved?
